### ISSUE TITLE
Add OS Images to PG omnispec

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#12]
The PG omnispec should allow the user to specify OS images to customize the nodes they allocate.

 _Imported from trac ticket [#12](http://trac.gpolab.bbn.com/gcf/ticket/12),  created by tmitchel on 09-27-2010 at 21:38, last modified: 09-28-2010 at 13:32_

**Comment by ahelsing** [comment]
There is now an "os" option with a default value of "FEDORA10-STD".  If an empty string is supplied then it gives you the default (latest linux release).   It would probably be better to use "" as the default instead of FEDORA10-STD but using FEDORA10-STD gives the user an example of what we're looking for.

_Trac comment by jkarlin on 09-28-2010 at 13:29_
