### ISSUE TITLE
Add a config setting for AM API version

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#159]
It'd be nice if you could use omni_config to control what version of the AM API you wanted to use.

 _Imported from trac ticket [#159](http://trac.gpolab.bbn.com/gcf/ticket/159),  created by jbs on 08-27-2012 at 16:42, last modified: 04-21-2014 at 13:33_

**Comment by ahelsing** [comment]
Most basic version: You can specify one version that you prefer.

More flexible version: You can supply a sorted list of versions that you prefer (akin to ssh_config's "Protocol 2,1" setting, to say "use protocol 2 if you can, 1 if you can't").

Most flexible version: Make it possible to override this on a per-AM basis, if you have AMs defined in your omni_config.

_Trac comment by jbs on 08-27-2012 at 16:43_

**Comment by seledwards** [comment]
Josh points out that he mostly uses omni with FOAM which only speaks v1 so this feature would be greatly appreciated by him.  And he thinks might be as well by others who use FOAM frequently.  

I'm going to assign to milestone 2.1 on the philosophy that we should do this sooner rather than later and we can reassign it later.

_Trac comment by sedwards (github user: seledwards) on 09-17-2012 at 15:53_

**Comment by ahelsing** [comment]
I already get updates to this ticket, since I'm the requestor.

_Trac comment by jbs on 09-17-2012 at 15:56_

**Comment by ahelsing** [comment]
Note: this ticket is part of milestone 2.1, which i'm about to close.  Someone should rehome it to some other milestone.

_Trac comment by chaos on 10-11-2012 at 12:39_

**Comment by ahelsing** [comment]
This has largely been made moot by the thing whereby a generic URL can now redirect you to an AM API version specific URL. I'll go ahead and close it out; if anyone else wants more than that, they can open a new ticket.

_Trac comment by jbs on 04-21-2014 at 13:33_
