### ISSUE TITLE
omni-configure overwrites omni_config when told not to

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#290]
I ran omni-configure.py from master ([cdae017e6de48edf0b26c16090f4931ec4545fa3](https://github.com/GENI-NSF/geni-tools/commit/cdae017e6de48edf0b26c16090f4931ec4545fa3)). When it asked if it should overwrite `/home/tmitchel/.gcf/omni_config` I said no, but it overwrote the file anyway.

Transcript:
```
$ src/omni-configure.py -f portal
INFO:omniconfig:Using configfile: /home/tmitchel/.gcf/omni_config
INFO:omniconfig:Using portal bundle /home/tmitchel/Downloads/omni-bundle.zip
INFO:omniconfig:Private key stored at: /home/tmitchel/.ssh/geni_key_portal
INFO:omniconfig:Script will create an extra public key file, based on the private key of the SSL cert/home/tmitchel/.ssl/geni_cert_portal.pem
INFO:omniconfig:

	CREATING SSH KEYPAIR
INFO:omniconfig:Private key stored at: /home/tmitchel/.ssh/geni_cert_portal_key
INFO:omniconfig:Public key stored at: /home/tmitchel/.ssh/geni_cert_portal_key.pub
File /home/tmitchel/.gcf/omni_config exists, do you want to replace it  [Y,n]?n
INFO:omniconfig:Your old omni configuration file has been backed up at /home/tmitchel/.gcf/omni_config-1
INFO:omniconfig:Wrote omni configuration file at: /home/tmitchel/.gcf/omni_config
```

 _Imported from trac ticket [#290](http://trac.gpolab.bbn.com/gcf/ticket/290),  created by tmitchel on 05-28-2013 at 22:09, last modified: 05-30-2013 at 11:32_

**Comment by innnkkki** [comment]
Fixed at [cc86cdc740bac507cf648bc23d11c5dba3e99997](https://github.com/GENI-NSF/geni-tools/commit/cc86cdc740bac507cf648bc23d11c5dba3e99997)

The problem is that there is only one default omni_config file (~/.gcf/omni_config) so if the new configuration file is written in a different place the user has to use the '-c' option and it is prone to user error. The right way to save it in a different file
is to use the '-c' option. 

To address this, added one more question to ensure that the user understands what's happening and give them a chance to bail if this is not what they want. Current execution:

 
 * Replace omni_config
```
File /home/geni/.gcf/omni_config exists, do you want to replace it  [Y,n]?y
INFO:omniconfig:Wrote omni configuration file at: /home/geni/.gcf/omni_config
```
  * Keep a backup file
```
INFO:omniconfig:Public key stored at: /home/geni/.ssh/geni_cert_portal_key.pub
File /home/geni/.gcf/omni_config exists, do you want to replace it  [Y,n]?n

'/home/geni/.gcf/omni_config' will be backed up at '/home/geni/.gcf/omni_config-3' and replaced with the new configuration file. Continue [Y,n]?y
INFO:omniconfig:Your old omni configuration file has been backed up at /home/geni/.gcf/omni_config-3
INFO:omniconfig:Wrote omni configuration file at: /home/geni/.gcf/omni_config
```
 * Want to keep the current omni_config
```
File /home/geni/.gcf/omni_config exists, do you want to replace it  [Y,n]?n

'/home/geni/.gcf/omni_config' will be backed up at '/home/geni/.gcf/omni_config-4' and replaced with the new configuration file. Continue [Y,n]?n

Exiting! To create a configuration file other than /home/geni/.gcf/omni_config use a different filename by using the '-c' option
```

Let me know if this is not what you had in mind. 

_Trac comment by nriga (github user: innnkkki) on 05-29-2013 at 21:30_
