### ISSUE TITLE
Automatically download the SFA certificate if necessary

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#3]
Add to omni the ability to download the SFA cert file listed in the configuration if it does not exist on disk.

 _Imported from trac ticket [#3](http://trac.gpolab.bbn.com/gcf/ticket/3),  created by tmitchel on 09-20-2010 at 16:00, last modified: 09-22-2010 at 14:07_

**Comment by ahelsing** [comment]
This is done.  If the cert file specified in the config file does not exist, omni will ask if you would like for omni to download it for you.  If yes, it creates (using openssl binary) a self-signed cert using the private/public keypair from the config, talks to the PL registry, and downloads the cert to the location specified by the config file.


It's debatable whether it's better to generate the self-signed cert in code rather than using openssl.  This requires pyOpenSSL to be installed.


_Trac comment by jkarlin on 09-22-2010 at 10:36_

**Comment by ahelsing** [comment]
Spoke with Tom, pyopenssl is preferred since gcf requires it anyway.

_Trac comment by jkarlin on 09-22-2010 at 11:49_

**Comment by ahelsing** [comment]
This is now done using the Python OpenSSL library instead of the binary.

_Trac comment by jkarlin on 09-22-2010 at 14:07_
