### ISSUE TITLE
stitching: rename fakeEndpoint

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#336]
The fakeEndpoint option inserts a fake endpoint, but from a user perspective its job is to allow stitching to a fixed switch endpoint. Rename the option something like --stitchToSwitch?

 _Imported from trac ticket [#336](http://trac.gpolab.bbn.com/gcf/ticket/336),  created by ahelsing on 08-05-2013 at 11:51, last modified: 08-08-2013 at 12:50_

**Comment by ahelsing** [comment]
Maybe `--switchEndpoint`?

_Trac comment by ahelsing on 08-06-2013 at 10:46_

**Comment by luisanevers** [comment]
I like --fixedEndpoint, it captures the scope a little more than --switchEndpoint. Although I think both would be acceptable.



_Trac comment by lnevers (github user: luisanevers) on 08-06-2013 at 11:09_

**Comment by ahelsing** [comment]
fixedEnpoint it is.


_Trac comment by ahelsing on 08-06-2013 at 11:31_

**Comment by luisanevers** [comment]
Verified in gcf-2.4-preview8:

Verified renaming and option being listed in README-stitching.txt and that the old option name is no longer recognized.

Created sliver successfully with this new option.  Although, was not able to exchange traffic  because the host at Stanford is no longer available.  Need to request  that some host be set up permanently to support this test scenario.

_Trac comment by lnevers (github user: luisanevers) on 08-08-2013 at 12:50_
