### ISSUE TITLE
add an acceptance test which runs getusercred

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#338]
Add an acceptance test which runs the omni `getusercred` command.  This test will be used to cache a user credential for a CH user, and have nagios report on whether the credential could be downloaded.

 _Imported from trac ticket [#338](http://trac.gpolab.bbn.com/gcf/ticket/338),  created by chaos on 08-05-2013 at 17:39, last modified: 09-06-2013 at 10:48_

**Comment by ahelsing** [comment]
Hi; just a reminder that this would be nice to have so that i can clean up some nagios checks which should/could use user credentials.

_Trac comment by chaos on 08-12-2013 at 09:59_

**Comment by ahelsing** [comment]
Ping.  This is still something i'd like for nagios check improvements.

_Trac comment by chaos on 08-19-2013 at 10:52_

**Comment by seledwards** [comment]
Pong.  It's the top of my list once I get through my morning email.

_Trac comment by sedwards (github user: seledwards) on 08-19-2013 at 10:59_

**Comment by seledwards** [comment]
Apparently we have different returns from `getusercred` based on the `api_version` and this should work either either.  (If you run with `-V 3` instead of just getting the usercred you get the usercred embedded in a structure with info about the cred.)

Run using:
```
./am_api_accept_nagios.py NagiosTest.test_getusercred_nagios
```

Outputs file to default location used by `getusercred`.

```
./am_api_accept_nagios.py NagiosTest.test_getusercred_nagios --usercredfile myusercred
```
Outputs file as `myusercred.xml`.

```
./am_api_accept_nagios.py NagiosTest.test_getusercred_nagios --usercredfile myusercred -V 3
```

Outputs file as `myusercred.json`

_Trac comment by sedwards (github user: seledwards) on 08-19-2013 at 13:42_

**Comment by seledwards** [comment]
Done and merged.

Git commit is `d397d9ebf133579bde15a899014cbb51b84521ef`.

_Trac comment by sedwards (github user: seledwards) on 08-19-2013 at 13:49_
