### ISSUE TITLE
If the AM is PG, the user URN must match the URN in the cert to install keys

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#34]
The URN of the user for installing keys has to match exactly the URN in the cert when PG is used as an AM. If the two do not match, the slice and sliver creation are successful but the user's keys are not installed at the host. If possible check user's URN against the URN at the cert and return an error to the user. 

 _Imported from trac ticket [#34](http://trac.gpolab.bbn.com/gcf/ticket/34),  created by nriga on 04-21-2011 at 21:41, last modified: 06-17-2011 at 11:44_
   CCing: nriga@...

**Comment by ahelsing** [comment]
This is only for PG AMs.

This is only for AMs that do not yet have Leigh's fix. I think that means after Tag v4.240? or stable-20110420? We'd used GetVersion to determine this, but we'd have to examine the git repo to see if this is enough. Note of course we'd need to make sure it's a PG AM somehow as well. Ugly.

If there is only 1 user in the omni_config, we could just use the URN from the cert. Otherwise, I think we just warn.

Omni code would look something like this:
```
            certurn = ''
            try:
                certurn = gid.GID(filename=self.framework.cert).get_urn()
            except Exception, exc:
                self.logger.warn("Failed to get URN from cert %s: %s", self.framework.cert, exc)
            if certurn != user['urn']:
                self.logger.warn("Keys MAY not be installed for user %s. In PG prior to stable-20110420, the user URN must match that in your certificate. Your cert has urn %s but you specified that user %s has URN %s. Try making your omni_config user have a matching URN.", user, certurn, user, user['urn'])
```



_Trac comment by ahelsing on 04-22-2011 at 09:54_

**Comment by tcmitchell** [comment]
This issue will appear in a diminishing set of ProtoGENI aggregates over time. The fix has been available as part of the stable branch for a couple of months. The limitation is [documented on the ProtoGENI wiki](https://www.protogeni.net/trac/protogeni/wiki/GeniAggregateManager#Priortostable-20110420). We should not add a check to omni for the small number of remaining aggregates that continue to have this limitation.

_Trac comment by tmitchel (github user: tcmitchell) on 06-17-2011 at 11:44_
