### ISSUE TITLE
omni does not timeout in an unresponsive AM

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#407]
ExoSM is currently unresponsive. It is up, i.e. you can telnet but never returns to the AM API calls. Omni should time out after a while and not just hang:

the time now is 9:29 and Omni is still stuck here
```
dhcp89-073-111:~ inki$ omni.py listresources -a eg-sm
09:13:45 INFO     omni: Loading agg_nick_cache file '/Users/inki/.gcf/agg_nick_cache'
09:13:45 INFO     omni: Loading config file /Users/inki/.gcf/omni_config
09:13:45 INFO     omni: Using control framework portal
09:13:45 INFO     omni: Substituting AM nickname eg-sm with URL https://geni.renci.org:11443/orca/xmlrpc, URN urn:publicid:IDN+exogeni.net+authority+am
```

 _Imported from trac ticket [#407](http://trac.gpolab.bbn.com/gcf/ticket/407),  created by nriga on 10-18-2013 at 09:30, last modified: 02-20-2014 at 13:30_

**Comment by ahelsing** [comment]
Probably the fix is to include a timeout when we create the client. See line 4769 of amhandler.py: the 4th arg is the timeout. I need to verify the units, what the default is, and that this timeout helps in the right cases: server not known, server not reachable, server never establishes a connection, server establishes a connection but never responds to calls - particularly that last one.


_Trac comment by ahelsing on 10-22-2013 at 10:21_

**Comment by ahelsing** [comment]
Units are seconds. It seems to do the right thing when the client hangs setting up the connection or handling it.

PG says 5-6 minutes is the max, so setting the default timeout to 6 minutes - which is pretty long, but at least not infinite.

This new timeout applies to connections to the CH as well.


_Trac comment by ahelsing on 10-24-2013 at 14:50_

**Comment by ahelsing** [comment]
On python 2.6 setting a timeout seems to cause things to hang indefinitely.

_Trac comment by ahelsing on 11-12-2013 at 16:56_

**Comment by ahelsing** [comment]
That only seems to be true at SAs, not at AMs. And more so at the SFA v2 SA than at the v1 SA for some unknown reason.

EG with a 10 second timeout it hangs at the new SFA SA, but gets a read timeout at the original SA. With a 100 second timeout the old SA gives an answer. Note that in both cases the call that actually gets stuck is retrieving the user credential.

_Trac comment by ahelsing on 11-12-2013 at 17:03_

**Comment by ahelsing** [comment]
Testing on illyrica, which has an OS / python version similar to Luisa's setup, I can reproduce her problem: With an ssltimeout set, the connection to the SFAv2 server for getusercred seems to hang for the length of the timeout. At the old SFA server, this is not true, and with no ssl timeout set, this is not true - in both those cases, the response is nearly immediate.
Testing against a hacked GCF AM I also cannot reproduce this problem: omni returns as soon as the AM returns, or when the timeout is reached, whichever is sooner.
Note that this is not specific to get_user_cred at the SFAv2 server. The same thing happens for get_ch_version.
I sent this information Tony.

At this point, I believe that this is somehow a bug on Tony's end, but I don't know how.


_Trac comment by ahelsing on 11-13-2013 at 10:45_

**Comment by ahelsing** [comment]
I emailed Tony for a status update.

_Trac comment by ahelsing on 11-19-2013 at 09:02_

**Comment by ahelsing** [comment]
Tony added a default timeout, and now it works.

_Trac comment by ahelsing on 11-19-2013 at 09:36_

**Comment by ahelsing** [comment]
(re) discovered that the fix applied here does not work on old versions of python 2.6, due to a known python bug:

http://bugs.python.org/issue5103

This was fixed late April 2010. So a python 2.6 newer than that would work. Apparently Ubuntu 10.04 however uses the older python that has this bug.

I'll note this in the omni readme.



_Trac comment by ahelsing on 02-20-2014 at 13:30_
