### ISSUE TITLE
`omni listresources slicename -o` generates many files for aggregates with no resources

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#423]
I spoke with an experimenter who was trying to determine which aggregates had resources in his slice.

I suggested:
```
omni listresources slicename -o
```

However this generates a large number of files which have RSpecs which contain no resources.

On further reflection he could then `cat` or `grep` the files that are produced by `listresources`, but this is started to get fairly complicated.

(Perhaps this is something for awemni.)

Experimenter is cc'd on this ticket.

 _Imported from trac ticket [#423](http://trac.gpolab.bbn.com/gcf/ticket/423),  created by sedwards on 11-05-2013 at 15:25, last modified: 10-17-2014 at 14:47_
   CCing: szb53@..., gpo-expt-support@...

**Comment by ahelsing** [comment]
Reassigning because 'gpo-exp' as an owner causes mail bounces.  If y'all need some sort of group owner for tickets on trac.gpolab ticketing systems, ping us (off this ticket) and we'll sort something out.

_Trac comment by chaos on 11-05-2013 at 15:49_

**Comment by ahelsing** [comment]
Ticket #133 is a similar but converse issue: I want files for aggregates with no info, because then I can use grep to look for things in *, and find files that don't contain the expected results -- whereas if those files don't exist at all, I can't do that.

Maybe this should be an option?

(Also, my use case is only in situations where I specify the aggregate to query; I never do a "ask every aggregate you know about" thing, so I don't personally much care if the behavior is different between those two. I do think that there's a use case here (for "I want to query all known aggregates for my stuff, and grep the results, so I need files even for aggregates that don't seem to have my stuff, so I can detect that") -- it's just not my personal use case.)

_Trac comment by jbs on 11-05-2013 at 16:27_

**Comment by seledwards** [comment]
I think using the new flag in omni 2.5 `--useSliceAggregates` to specify aggregates (instead of not specifying or using `-a`) does a lot to alleviate this issue.

_Trac comment by sedwards (github user: seledwards) on 04-02-2014 at 10:40_

**Comment by ahelsing** [comment]
useSliceAggregates covers the desire here.

_Trac comment by ahelsing on 10-17-2014 at 14:47_
