### ISSUE TITLE
Rename default omni_config

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#83]
The default omni_config in the top level gcf directory should have another name (eg omni_config.sample) so that when you run from the top level directory it doesn't use the default omni_config instead of the omni_config in .gcf

 _Imported from trac ticket [#83](http://trac.gpolab.bbn.com/gcf/ticket/83),  created by sedwards on 01-03-2012 at 16:32, last modified: 01-31-2012 at 16:07_
   CCing: gpo-sw-dev@..., nriga@...

**Comment by tcmitchell** [comment]
Using `omni_config` as the name in the top-level directory makes it easy to run right out of the box. It does have the unfortunate consequence of overriding an `omni_config` file in the `.gcf` directory. The original thought was that a local file would override a file in `$HOME/.gcf`. I'm not sure what the right solution is, but we should consider the options and see if there is a better way to satisfy these competing interests.

_Trac comment by tmitchel (github user: tcmitchell) on 01-03-2012 at 16:53_

**Comment by innnkkki** [comment]
A solution would be to rename it to something like omni_config_sample and have as a first step of the getting started instructions, to copy it or create a symlink to 
omni_config. 

_Trac comment by nriga (github user: innnkkki) on 01-18-2012 at 10:46_

**Comment by ahelsing** [comment]
Similar to the problem of shadowing the one in ~/.gcf it causes problems in git clones because omni_config is tracked, making it difficult to pull updates when you've modified it (something you are basically forced to do).  This is also a problem for the omni_config in the AM acceptance tests, as well as request.xml, request2.xml, and request3.xml.  All of these files should be either *.[example|sample], or in the case of the request[23].xml files, I think just not included at all.

_Trac comment by nick.bastin on 01-18-2012 at 10:55_

**Comment by ahelsing** [comment]
Replying to [nriga](comment:3):
> A solution would be to rename it to something like omni_config_sample and have as a first step of the getting started instructions, to copy it or create a symlink to 
> omni_config. 

Even better, IMHO, would before GCF to only look for config files in places where config files should go, rather than in the source. Have the docs say to put your omni_config (and whatever else) in .gcf, and voila.

Why does it ever need to look in the current directory, anyway?

(Ditto other things, like rspecs for regression tests -- have a default location where it looks for them (outside of the source tree), allow you to specify an alternate location, don't assume that they config files are in the source.)

_Trac comment by jbs on 01-18-2012 at 10:57_

**Comment by seledwards** [comment]
I spoke with Niky and she reiterated her opinion that it would be fine to just have users copy a sample omni_config.SOMETHING to the appropriate place.

I'm renaming omni_config to be omni_config.orig and changing the instructions to say to copy omni_config.orig to .gcf/omni_config.

I'll look at request*.xml in a minute.

_Trac comment by sedwards (github user: seledwards) on 01-30-2012 at 14:02_

**Comment by seledwards** [comment]
Should probably make the same change to gcf_config.  Will rename gcf_config to gcf_config.orig and change the instructions to match.

_Trac comment by sedwards (github user: seledwards) on 01-30-2012 at 14:18_

**Comment by seledwards** [comment]
Changed gcf_config.orig to gcf_config.sample and omni_config.orig to omni_config.sample.  And changed associated docs.

_Trac comment by sedwards (github user: seledwards) on 01-31-2012 at 10:26_

**Comment by seledwards** [comment]
Finally, renaming request.xml, request2.xml, request3.xml, and bad.xml as *.xml.sample.

Updated acceptance tests README appropriately.

Closing ticket.

_Trac comment by sedwards (github user: seledwards) on 01-31-2012 at 16:07_
