### ISSUE TITLE
Incorrect Slice Credentials written to file 

### ISSUE THREAD

**Issue by hussamnasir** [GENI-NSF/geni-tools#868]
When using speaks-for to fetch a slicecredential where in 
--slicecredfile=<somefile>
--output=True 
are set, getslicecred call basically never gets called at the Slice Authority. Instead the same expired credential read from the file provided via --slicecredfile is written back to the same file. The fault lies in the "def _get_slice_cred(handler, urn):" in handler_util.py.

A work around is for the user to zero out the contents of the file before calling getSlicecred.

**Comment by ahelsing** [comment]
I don't think this is specific to speaks for. Looks like if you do `getslicecred` and specify `--slicecredfile` pointing to a file of non 0 size, then that is what gets returned. Regardless of speaks for or if the credential is expired.

Arguably this is a feature: You can call `getslicecred`, and it will return fast because you already have it downloaded. But if the credential is expired and the slice itself has been renewed, this is problematic.

As you note, 1 workaround: 0 out the file. Another workaround is to use a different filename.

Some options for changes in Omni:
 1. Add a flag so calling `getslicecred` ignores any saved slice cred if desired
 2. `getslicecred` ignores any saved slice cred if you also specified `--output` (on the theory that this indicates your desire to save a new slice cred)
 3. `getslicecred` ignores any saved slice cred if that cred is expired or otherwise invalid
 4. `getslicecred` always ignores any saved slice cred
 5. Option 2&3 combined

Any opinions?

If we do options 1 or 2 or 4, the fix should be in chhandler (through moving the file in `--slicecredfile` out of the way and back). Option 3 could be implemented in `handler_utils._get_slice_cred` perhaps, though we should be careful as this gets used by many Omni calls.

**Comment by hussamnasir** [comment]
I think we should go with 4, because the operation name suggests that 
the credential is to be fetched.

cheers,

Hussam
(Hussamuddin Nasir)

Netlab Operations Team

-------------------------------------------------------------------
Laboratory for Adv. Networking  Phone  : (859)218-0059
James F Hardymon Building       Fax    : (859)323-3740
301 Rose Street, Rm 237         E-mail : nasir@netlab.uky.edu
Lexington, KY 40506-0495        Web    : http://www.netlab.uky.edu

                         University of Kentucky
                         **********************
-------------------------------------------------------------------

**Comment by ahelsing** [comment]
Fixed as you requested.

**Comment by hussamnasir** [comment]
Thanks.. :)

cheers,

Hussam
(Hussamuddin Nasir)

Netlab Operations Team

-------------------------------------------------------------------
Laboratory for Adv. Networking  Phone  : (859)218-0059
James F Hardymon Building       Fax    : (859)323-3740
301 Rose Street, Rm 237         E-mail : nasir@netlab.uky.edu
Lexington, KY 40506-0495        Web    : http://www.netlab.uky.edu

                         University of Kentucky
                         **********************
-------------------------------------------------------------------
